name: Kernel Help Compiler CI

on:
  workflow_dispatch:
      inputs:
        MODEL_TYPE:
          description: 'DEVICE CODENAME'
          default: SM-J710X
          type: choice
          options:
            - "SM-J530X" 
            - "SM-J730X" 
            - "SM-J710X" 
            - "SM-J701X" 
            - "SM-G610X" 
            - "SM-J600X" 
            - "SM-A600X"
          required: true
        VARIANT_TYPE:
          description: 'BUID VARIANT'
          default: Treble
          type: choice
          options:
            - "Treble" 
            - "oneUI"
          required: true
        VARIANT_VERSION:
          description: 'KERNEL VERSION'
          default: V5.0
          type: choice
          options:
            - "V6.0" 
            - "V5.0" 
            - "V4.0"
            - "V3.0"
            - "V2.0" 
            - "V1.0"
          required: true
        VARIANT_NAME:
          description: 'KERNEL NAME'
          default: CronosKernel
          required: true

        VARIANT_MODEM:
          description: 'ANDROID MODEM VERSION'
          default: '7'
          type: choice
          options:
            - '7'
            - '8'
            - '9'
          required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
      
    - name: Delete failed workflow runs
      run: |
        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
             -H "Accept: application/vnd.github.v3+json" \
             https://api.github.com/repos/${{ github.repository }}/actions/runs \
             | jq -r '.workflow_runs[] | select(.conclusion == "failure") | .id' \
             | xargs -I {} curl -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
             -H "Accept: application/vnd.github.v3+json" \
             https://api.github.com/repos/${{ github.repository }}/actions/runs/{}
             
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential linux-headers-$(uname -r) libncurses-dev gawk flex bison openssl libssl-dev dkms libelf-dev libudev-dev libpci-dev libiberty-dev autoconf llvm git ccache

    - name: Start compilation
      run: |
        chmod +x Cronos_no_interaction.sh
        ./Cronos_no_interaction.sh ${{ github.event.inputs.MODEL_TYPE }} ${{ github.event.inputs.VARIANT_TYPE }} ${{ github.event.inputs.VARIANT_VERSION }} ${{ github.event.inputs.VARIANT_NAME }} ${{ github.event.inputs.VARIANT_MODEM}}
        
    - name: Upload ${{ github.event.inputs.MODEL_TYPE }} Image Generated
      uses: actions/upload-artifact@v4
      with:
       name: kernel-image-${{ github.event.inputs.MODEL_TYPE }}
       path: /home/runner/work/HeliosPro_Kernel_7870/HeliosPro_Kernel_7870/Cronos/Product/CronosKernel-V*-*-*.zip
       if-no-files-found: warn  # Optional
   
    - name: Upload ${{ github.event.inputs.MODEL_TYPE }} Zip Generated
      uses: actions/upload-artifact@v4
      with:
       name: kernel-${{ github.event.inputs.MODEL_TYPE }}-Zip
       path: /home/runner/work/HeliosPro_Kernel_7870/HeliosPro_Kernel_7870/Cronos/Product/${{ github.event.inputs.VARIANT_NAME }}-V*-*-*-*.img
       if-no-files-found: warn  # Optional
    
