name: Kernel Compiler CI

on:
  push:
    branches:
    - main
    - Cronos
    - default
    - OSRC
    - Pie
    - Treble-9.0
    - master
  pull_request:
    branches:
    - main
    - Cronos
    - default
    - OSRC
    - Pie
    - Treble-9.0
    - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        menuvar: [ "SM-J730X", "SM-J710X" ]
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential linux-headers-$(uname -r) libncurses-dev gawk flex bison openssl libssl-dev dkms libelf-dev libudev-dev libpci-dev libiberty-dev autoconf llvm git ccache

    - name: Start compilation
      run: |
        chmod +x Cronos_no_interaction.sh
        ./Cronos_no_interaction.sh ${{ matrix.menuvar }}
        
    - name: Upload Image Generated
      uses: actions/upload-artifact@v4
      with:
       name: kernel-image-${{ matrix.menuvar }}
       path: /home/runner/work/HeliosPro_Kernel_7870/HeliosPro_Kernel_7870/Cronos/Product/CronosKernel-V*-*-*.zip
       if-no-files-found: warn  # Optional
   
    - name: Upload Zip Generated
      uses: actions/upload-artifact@v4
      with:
       name: kernel-${{ matrix.menuvar }}-Zip
       path: /home/runner/work/HeliosPro_Kernel_7870/HeliosPro_Kernel_7870/Cronos/Product/CronosKernel-V*-*-*-*.img
       if-no-files-found: warn  # Optional
    
