name: Kernel Help Compiler CI

on:
  workflow_dispatch:
      inputs:
        RUN_OS_VERSON:
          required: true
          description: "MACHINE ON RUN CODE"
          type: choice
          options:
            - ubuntu-latest
            - ubuntu-22.04
            - ubuntu-20.04
          default: ubuntu-latest

        MODEL_TYPE:
          required: true
          description: 'DEVICE CODENAME'
          type: choice
          options:
            - "SM-J530X" 
            - "SM-J730X" 
            - "SM-J710X" 
            - "SM-J701X" 
            - "SM-G610X" 
            - "SM-J600X" 
            - "SM-A600X"
          default: SM-J710X

        VARIANT_TYPE:
          required: true
          description: 'BUID VARIANT'
          type: choice
          options:
            - "Treble" 
            - "oneUI"
          default: Treble

        VARIANT_VERSION:
          required: true
          description: 'KERNEL VERSION'
          type: choice
          options:
            - "V6.0" 
            - "V5.0" 
            - "V4.0"
            - "V3.0"
            - "V2.0" 
            - "V1.0"
          default: V5.0

        VARIANT_NAME:
          required: true
          description: 'KERNEL NAME'
          default: CronosKernel

        VARIANT_MODEM:
          required: true
          description: 'ANDROID MODEM VERSION'
          type: choice
          options:
            - 7
            - 8
            - 9
          default: '7'
jobs:
  build:
    runs-on: ${{ github.event.inputs.RUN_OS_VERSON }}
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
      
    - name: Delete failed workflow runs
      run: |
        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
             -H "Accept: application/vnd.github.v3+json" \
             https://api.github.com/repos/${{ github.repository }}/actions/runs \
             | jq -r '.workflow_runs[] | select(.conclusion == "failure") | .id' \
             | xargs -I {} curl -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
             -H "Accept: application/vnd.github.v3+json" \
             https://api.github.com/repos/${{ github.repository }}/actions/runs/{}
             
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential linux-headers-$(uname -r) libncurses-dev gawk flex bison openssl libssl-dev dkms libelf-dev libudev-dev libpci-dev libiberty-dev autoconf llvm git ccache

    - name: Start compilation
      run: |
        chmod +x Cronos_no_interaction.sh
        ./Cronos_no_interaction.sh ${{ github.event.inputs.MODEL_TYPE }} ${{ github.event.inputs.VARIANT_TYPE }} ${{ github.event.inputs.VARIANT_VERSION }} ${{ github.event.inputs.VARIANT_NAME }} ${{ github.event.inputs.VARIANT_MODEM }}

    - name: Upload ${{ github.event.inputs.MODEL_TYPE }} Image Generated
      uses: actions/upload-artifact@v4
      with:
       name: kernel-image-${{ github.event.inputs.MODEL_TYPE }}
       path: /home/runner/work/HeliosPro_Kernel_7870/HeliosPro_Kernel_7870/Cronos/Product/${{ github.event.inputs.VARIANT_NAME }}-V*-*-*.zip
       if-no-files-found: warn  # Optional
   
    - name: Upload ${{ github.event.inputs.MODEL_TYPE }} Zip Generated
      uses: actions/upload-artifact@v4
      with:
       name: kernel-${{ github.event.inputs.MODEL_TYPE }}-Zip
       path: /home/runner/work/HeliosPro_Kernel_7870/HeliosPro_Kernel_7870/Cronos/Product/${{ github.event.inputs.VARIANT_NAME }}-V*-*-*-*.img
       if-no-files-found: warn  # Optional
    
